### ISSUE TITLE
Incorrect version tag

### ISSUE THREAD

**Issue by kiesia** [thriveweb/photoswipe-masonry-v2#7]
I'm not sure how tagging works for wordpress plugins, but [something weird has happened](https://plugins.svn.wordpress.org/photoswipe-masonry/tags/). I'm pretty sure you meant to tag version 4.6.1 as 1.2.4?

**Comment by thriveweb** [comment]
Hi kiesia. Yes that was a mistake. I think it was fixed? WP is showing the correct version.

**Comment by kiesia** [comment]
Ah it's showing up now. The incorrect tag is still showing up on [wpackagist](https://wpackagist.org/search?q=photoswipe-masonry&type=any&search=). Not sure if you can do anything about that, it's a bit confusing though.
